// Note: This file was originally generated by Genie

//===============================================================================
//
// IErrorLog
//
// PURPOSE: 
// Biz object interface.
//
// NOTES: 
// 
//
//===============================================================================
//
// Copyright (C) 2008 
// All rights reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED 'AS IS' WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

// Required for DateTime

namespace Agile.Mobile.Web.Logging
{

		/// <summary>
		/// Biz object interface.
		/// </summary>
	public partial interface IErrorLog : IErrorLogData
	{

	}

}
